language: java
jdk:
  - oraclejdk7
  - oraclejdk8
addons:
  apt:
    packages:
      - rpm
before_deploy:
  - mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
  - mvn rpm:rpm && export RELEASE_RPM_FILE=$(ls target/rpm/plugin-output-splunk/RPMS/noarch/plugin-output-splunk-*.rpm)
  - export RELEASE_PKG_FILE=$(ls target/plugin-output-splunk-*.jar)
  - echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: "LjGKvDU17hZNjjZG7iDkPpuwfEODec44Ed+cl7QRkvqzfDPS/dKERNBfIwxHDN8hPd0OLFzB6hBD5jprg2ypygg81h18autHNCm1mvAZ0FI4zh4H+3f/IZrrJXO4CkVbz37GyrFOeU6ktFyeClhsL0h9KK7d7C1EkQLe/6xnhi0deBporotf0TBHQ8rhJWtkhONP3gGaA5LLefpriF+G5MBY2vxJoLlO9kzSj4/G7tgP5nZwyhq4AWQ8hS7cNKoXFRb9Wn9yhQ8gbpEdP+M6RNQpLL+MaFFc9K0MPQoalOwq0NNj5arzqoowagmR4xTKkuYhHFR748At3HwXt1MxoodfQlKN8o82x8UVSdSppC5CpIbVdNgbn/oDCLRpRSvIgn+Al5o4kaPTe77PpHRCpsCcD4D2wpsy5aw4GT2MyNnt3m0oPgWUYx/n3sWq4yfxSUE+BQwTnr/6AD1I3NZCZmGiDNQO3Gpxry5pDjKd3mAQO402evRPkJpVYoq4XOMMyNzq7MIHGvt45e1tJMVUeT9Y+yISRP+VsYvdDbNfxS2q71QSUYMlby1SvJqzZbnk582KmhehlQ8SbSl5S2jMkx+iecqeH/NZw4VyQL7PHkbifdDkjLgqGXEvHZK/2ZXLzj/iy8EpLmTW+NxRnPPbM+7H5WrzsHacCgeKCsQGyac="
  file: 
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk7
